const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('api', {
  openAudio: () => ipcRenderer.invoke('dialog:openAudio'),
  openLyrics: () => ipcRenderer.invoke('dialog:openLyrics'),
  saveTTML: (content, name, defaultDir) => ipcRenderer.invoke('dialog:saveTTML', content, name, defaultDir),
  saveLRC: (content, name, defaultDir) => ipcRenderer.invoke('dialog:saveLRC', content, name, defaultDir),
  writeFileDirect: (filePath, content) => ipcRenderer.invoke('file:writeDirect', filePath, content),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  getPlatform: () => ipcRenderer.invoke('app:getPlatform'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  readBinary: (fp) => ipcRenderer.invoke('file:readBinary', fp),
  fileExists: (fp) => ipcRenderer.invoke('file:exists', fp),
  getAudioMetadata: (fp) => ipcRenderer.invoke('audio:getMetadata', fp),
  getWaveformPeaks: (fp, points) => ipcRenderer.invoke('waveform:getPeaks', fp, points),
  hasNativeWaveformDecoder: () => ipcRenderer.invoke('waveform:hasNativeDecoder'),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window:toggleMaximize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  isWindowMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  onWindowMaximized: (fn) => ipcRenderer.on('window:maximized', (_, value) => fn(value)),
  getProjectsDir: () => ipcRenderer.invoke('project:getDir'),
  autosaveProject: (name, json) => ipcRenderer.invoke('project:autosave', name, json),
  saveProject: (filePath, json) => ipcRenderer.invoke('project:save', filePath, json),
  saveProjectAs: (json, suggestedName) => ipcRenderer.invoke('project:saveAs', json, suggestedName),
  openProjectDialog: () => ipcRenderer.invoke('project:openDialog'),
  saveThemeAs: (json, suggestedName) => ipcRenderer.invoke('theme:saveAs', json, suggestedName),
  openThemeDialog: () => ipcRenderer.invoke('theme:openDialog'),
  listProjects: () => ipcRenderer.invoke('project:list'),
  listAutosaves: () => ipcRenderer.invoke('project:listAutosaves'),
  loadProjectFile: (filePath) => ipcRenderer.invoke('project:load', filePath),
  deleteProjectFile: (filePath) => ipcRenderer.invoke('project:delete', filePath),
  deleteAutosavesForSong: (name) => ipcRenderer.invoke('project:deleteAutosavesForSong', name),
  showInFolder: (filePath) => ipcRenderer.invoke('shell:showInFolder', filePath),
  openProjectsFolder: () => ipcRenderer.invoke('shell:openProjectsFolder'),
  confirmCloseResult: (shouldClose) => ipcRenderer.invoke('window:confirmCloseResult', shouldClose),
  onConfirmClose: (fn) => ipcRenderer.on('app:confirm-close', () => fn()),
})