name: Build Electron Executable

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git Ref/Tag/Commit to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Portable Windows App
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lokal-TTML-Editor-Executable
          path: release/Lokal-TTML-Editor.exe
